[workspace]
resolver = "2"
members = [
  "contracts/subscription_contract",
  "contracts/merchant_vault_contract",
  "contracts/payment_registry_contract",
  "contracts/escrow_contract",
  "contracts/payment_split_contract",
  "contracts/hello_world",
  "contracts/fraud_detection_contract",
  "contracts/atomic_swap_contract",
  "contracts/liquidity_pool_contract",
  "contracts/orchestration_contract",
]

[workspace.dependencies]
soroban-sdk = "27.0.6"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# For more information about this profile see https://soroban.stellar.org/docs/basic-tutorials/logging#cargotoml-profile
[profile.release-with-logs]
inherits = "release"
debug-assertions = true
